### ISSUE TITLE
YouTube link is broken

### ISSUE THREAD

**Issue by luismarques** [laanwj/pmodoled#1]
The YouTube video link shows as "Video unavailable" (at least in the UK).

**Comment by laanwj** [comment]
Strange, same here! I wonder why; I'm sure it worked at some point and didn't delete it intentionally at least.
Will try to see if I can find it with my other videos later.

**Comment by laanwj** [comment]
No that video seems really gone, the only video in my uploads with a PMOD OLED is https://www.youtube.com/watch?v=iddlm9BSnWo, where I was driving it from an FPGA instead of the SiFive board.

Sorry! Will remove the link.

**Comment by luismarques** [comment]
No problem. It was just an FYI.
